### PR TITLE
Use newer containerApp API version

### PR DESCRIPTION
**Pull request by Benjiiim**
## Why make this change?

To avoid the WorkloadProfilePropertyNotSupportedInApiVersion that can occur with containerApp API version 2022-10-01 when deploying with the bicep file.

Error with the [az deployment group create command](https://github.com/Azure/data-api-builder/blob/31429e504132843914bf84409fbdd1cddf571751/samples/azure/azure-container-apps-deploy.sh#L107) in the azure-container-apps-deploy.sh file:

> ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/xx-xx-xx-xx-xx/resourceGroups/Alpha_API_Tests_Auto_6/providers/Microsoft.Resources/deployments/dab-on-aca","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"WorkloadProfilePropertyNotSupportedInApiVersion","message":"WorkloadProfiles configuration is not supported in 2022-10-01 api version. Use 2022-11-01-preview or above."}]}}

## What is this change?

Upgrade the containerApp API version in the bicep file to the last stable version.

## How was this tested?

Manual testing

## Sample Request(s)

azure-container-apps-deploy.sh

### CODE REVIEW

**Comment by seantleonard** [comment]
Hi @Benjiiim , can you highlight what documentation step failed with the old value? Are there any doc updates required to align with this api version bump?

**Comment by Benjiiim** [comment]
Details added above.

No doc update needed as the [corresponding doc](https://learn.microsoft.com/en-us/azure/data-api-builder/running-in-azure#use-azure-container-apps) is only mentioning the existence of this sample:

`A sample shell script that can be run on Linux (using the [Cloud Shell](https://learn.microsoft.com/en-us/azure/cloud-shell/overview) if you don't have a Linux machine or WSL installed) is available in [/samples/azure](https://github.com/Azure/data-api-builder/tree/main/samples/azure) folder.`

**Review by seantleonard — APPROVED** [review]

**Review by aaronburtle — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
