### PR TITLE
add current version number

### PR DESCRIPTION
**Pull request by yorek**
## Why make this change?

Add a default version that is aligned with what being built to be able to more easily identify the correct version of a dab application connected to MSSQL (or another supported database)

## What is this change?

The change adds current version information to the project files.

## How was this tested?

- [x] Integration Tests
- [x] Unit Tests

## Notes

With this change, querying MSSQL to find the connected DAB instances will return also correct version information:

```sql
select session_id, host_name, program_name, client_interface_name 
from sys.dm_exec_sessions where is_user_process = 1 and program_name like '%dab%'
```

result:

image

### CODE REVIEW

**Comment by abhishekkumams** [comment]
adding the version in project file will override the version that is generated automatically in build. Therefore, it makes things more manual. we need to find some better way.

**Comment by Aniruddh25** [comment]
> adding the version in project file will override the version that is generated automatically in build. Therefore, it makes things more manual. we need to find some better way.

build automatically generates only the patch number. Major/Minor versions are hard coded in the build pipeline, and since `FileTransform` will only be useful for automated builds, I guess the only way to have these versions in local cloned builds is adding them in the csproj files as well.

**Review by Aniruddh25 — APPROVED** [review]

**Review by Aniruddh25 — COMMENTED** [review]
There seems to be some unit tests in the CLI project that are failing which still are expecting 1.0.0 version.

**Comment by abhishekkumams** [comment]
> > adding the version in project file will override the version that is generated automatically in build. Therefore, it makes things more manual. we need to find some better way.
> 
> build automatically generates only the patch number. Major/Minor versions are hard coded in the build pipeline, and since `FileTransform` will only be useful for automated builds, I guess the only way to have these versions in local cloned builds is adding them in the csproj files as well.

We can't merge this PR, before updating the `FileTransform` task, because the version hardcoded in csproj file will take precedence over the nuget pack command that we have in build pipeline. this will create an issue as it won't use the generated version.

**Comment by seantleonard** [comment]
> > > adding the version in project file will override the version that is generated automatically in build. Therefore, it makes things more manual. we need to find some better way.
> > 
> > 
> > build automatically generates only the patch number. Major/Minor versions are hard coded in the build pipeline, and since `FileTransform` will only be useful for automated builds, I guess the only way to have these versions in local cloned builds is adding them in the csproj files as well.
> 
> We can't merge this PR, before testing the `FileTransform` task, because the version hardcoded in csproj file will take precedence over the nuget pack command that we have in build pipeline. this will create an issue as it won't use the generated version.

What specific steps are needed beyond ensuring existing pipelines pass? What logic does ` nuget pack command that we have in build pipeline.` have and can we update that to accommodate this change?

**Comment by seantleonard** [comment]
closing because this functionality was fixed in #2086

**Pull request closed without merging**
