### PR TITLE
[Cherry pick] Table name collision bug fix (#1990)

### LINKED ISSUE #1908: [Bug]: DAB seems to have issues with tables in different schemas that have the same name (SQL Server)
### What happened?

I have two tables with the same name, in two different schemas, in the same database:
schema1.tablename and 
schema2.tablename
I add them both to the "entities" section in dab-config.json, like this:

  "schema1_tablename": {
    "source": "schema1.tablename",
    "permissions": [
      {
        "actions": ["*"],
        "role": "anonymous"
      }
    ]
  },
  "schema2_tablename": {
    "source": "schema2.tablename",
    "permissions": [
      {
        "actions": ["*"],
        "role": "anonymous"
      }
    ]
  },

When I try to query the first using REST via /api/schema1_tablename, I get the right answer: a list of the rows.
When I try to query the second using REST via /api/schema2_tablename I get an error 500 that says "Invalid Column Name".  The column it names is a valid column in the schema1 table, but not in the schema2 table.  

If I reverse the order of the entities in the dab-config.json, then I can query the schema2 table, but not the schema1 table.  So, even though in the configuration I am providing the full name of the table using schema.tablename format, it doesn't seem capable of distinguishing between tables that have the sane tablename, even if the schema is different.

### Version

Microsoft.DataApiBuilder 0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI), Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by seantleonard**
Cherry picks to `release/0.11` from `main`

## Why make this change?

Closes #1908

## What is this change?

We were previously filling the schema information for the entity data set but only using the table name. We add in the schema name to deconflict between two tables with the same name in different schemas. This means that we retrieve information from the entity data set by using schema and tablename when schema is available, and just the table name otherwise.

The reason that we do not need to worry about collisions at the schema and table name level (eg. where we have the same schema and table names within different databases) is because this entity data set is a part of the SqlMetadataProvider, and we have a SqlMetadataProvider for each database (not database type but actual DBs).

## How was this tested?

A regression test with a collision between table names in different schemas was added. We also update the unit test for SqlMetadatProvider.

### CODE REVIEW

**Review by Aniruddh25 — APPROVED** [review]
LGTM, thanks for the port

**Review by aaronburtle — APPROVED** [review]

**Pull request merged**
