### PR TITLE
[CherryPick] Upgrade dependencies, pipeline tasks, pipeline variables #1970 #1955 #1928 #1954

### PR DESCRIPTION
**Pull request by seantleonard**
#1970 #1955 #1928 #1954

Updates dependencies:
- Microsoft.AspNetCore.Authentication.JwtBearer
- Microsoft.Data.SqlClient
- Microsoft.IdentityModel.JsonWebTokens
- System.IdentityModel.Tokens.Jwt

Update pipeline task:
- `NuGetAuthenticate@0` to `NuGetAuthenticate@1`
- LocalDB connection string default set instead of depending on private env_var.
- Auto generate db passwords and append to connection strings during each pipeline run

Other changes to support the changes above:
- Suppress NU1603 warning as error for all projects
- Update ConfigurationTests jwt token creation to handle breaking changes in newer versions of Jwt* dependencies.

All related to pipeline updates that are required for 0.10 stable.

### CODE REVIEW

**Review by abhishekkumams — APPROVED** [review]

**Review by ayush3797 — APPROVED** [review]

**Comment by seantleonard** [comment]
> nit: Fix PR title to mention at high level what the cherry picks are about

Done. Also added brief summary to PR description capturing all the changes.

**Pull request merged**
