### PR TITLE
Migrate MYSQL and PGSQL Integration test pipeline

### LINKED ISSUE #1923: Pipeline Migration

### PR DESCRIPTION
**Pull request by abhishekkumams**
## Why make this change?

- Closes #1923 
- As part of pipeline migration.

## How was this tested?
- pipeline running fine

### CODE REVIEW

**Review by seantleonard — APPROVED** [review]
Thanks for migrating these!

**Review by Aniruddh25 — APPROVED** [review]
Thanks for the quick fix!

**Review by severussundar — APPROVED** [review]

**Pull request merged**
