### PR TITLE
Multiple-Create : Feature

### PR DESCRIPTION
**Pull request by ayush3797**
## Why make this change?

-  All code changes for **Multiple Create** feature was being merged into `dev/NestedMutations` branch. 
- This PR attempts to merge all these changes to the `main` branch in preparation for the `0.12.* rc1` release 

## What is this change?

-  Right now, `dev/NestedMutations` branch contains the code changes for the following components of Multiple Create feature 
  - Schema Generation - https://github.com/Azure/data-api-builder/pull/1902
  - AuthZ - https://github.com/Azure/data-api-builder/pull/1943
  - Feature flag - CLI changes https://github.com/Azure/data-api-builder/pull/1983
  - Feature flag - Re-naming changes https://github.com/Azure/data-api-builder/pull/2103
  - Feature flag - Engine changes https://github.com/Azure/data-api-builder/pull/2116 
- Each specified PR was reviewed before merging into `dev/NestedMutations` branch.
- This PR aims to merge all the changes into `main` branch
  
## How was this tested?

- [x] Unit, Integration and Manual tests were performed on each PR before merging into `dev/NestedMutations`

### CODE REVIEW

**Review by severussundar — APPROVED** [review]

**Review by seantleonard — APPROVED** [review]
Thanks for adding this. 

Nit for next time: please rebase this branch onto latest main before opening so the commit history is cleaner.
- Noise of the merge and revert of [Adding validation to disallow multiple relationships between same source and target entities](https://github.com/Azure/data-api-builder/pull/2122/commits/e850ead77ec3d8423562b009d9f616e7a92c2ff9) 
- Noise of merging latest main

and documentation of additional commits that are relevant beyond the PRs:
1. https://github.com/Azure/data-api-builder/pull/2122/commits/75b06c0477e8bbfa03c1ebee4ff675b4cd067ac0 ([adds logic to throw exp when source is null; got missed during merge with latest main](https://github.com/Azure/data-api-builder/pull/2122/commits/75b06c0477e8bbfa03c1ebee4ff675b4cd067ac0)

**Pull request merged**
