### PR TITLE
Move to file scoped namesspace project Auth

### PR DESCRIPTION
**Pull request by gmottajr**
It was requested to move to file scoped namespace.

### CODE REVIEW

**Review by Aniruddh25 — APPROVED** [review]
Looks good to merge! Thank you for your contributions @gmottajr and splitting the PR #1661 into smaller chunks - so easy to review :)

**Review by seantleonard — APPROVED** [review]
Thank you for making these changes! 

Note to other reviewers: using VSCode w/ GitHub Pull Request extension to review highlights the actual changes (2 lines in each file` and not the whole file like the GitHub web UI.

**Review by abhishekkumams — APPROVED** [review]

**Comment by gmottajr** [comment]
Awesome, thank you so much!

**Pull request merged**
