### PR TITLE
Move to file scoped namespaces

### PR DESCRIPTION
**Pull request by gmottajr**
This is an issue posted in GitHUb #1595

It has been requested a refactoring moving to file scoped namespace.

### CODE REVIEW

**Comment by seantleonard** [comment]
Hi @gmottajr thank you for contributing this change!

It would be really helpful for reviewers to divide this change into multiple PRs scoped to a per project basis. That way, the lower file count will reduce feedback turnaround time and thus get your changes merged quicker.

Looks like you already have your commits broken down into consumable chunks so that would be a good place to start.

**Comment by gmottajr** [comment]
@microsoft-github-policy-service agree.

This is my status: I have sole ownership of intellectual property
rights to my Submissions and I am not making Submissions in the course
of work for my employer.

I'm not sure whether or not I'm answering the way expected. Please let
me know if I need to do anything differently, since this is my first
time contributing with any open source initiative.

Thank you very much.

**Comment by gmottajr** [comment]
@microsoft-github-policy-service agree company=no company specified

**Comment by seantleonard** [comment]
Hi @gmottajr,

Can you divide this change into multiple PRs -- scoped to a per project basis? (e.g. Core, Service, CLI, Service.Tests, Config). That will enable reviewers to provide quicker reviews incrementally.

There are currently 239 files changes, where GitHub unfortunately shows many changes when, in reality, just the file scoped namespaces were added.

**Comment by gmottajr** [comment]
Sure, no problem. I will be working on it and let you know asap.
Thank you very much.

**Pull request closed without merging**
