### PR TITLE
Fixed duplicate datarow issue

### LINKED ISSUE #2255: [Test Bug] Fix GraphQLSupportTypesTestsBase.cs datarows for QueryTypeColumn test.
The following datarows are duplicates and just need to specify id values 1,2,3,4, respectively.
image

https://github.com/Azure/data-api-builder/blob/7215f1a499b6f61dce200ffe92f6f0cbdb44e49e/src/Service.Tests/SqlTests/GraphQLSupportedTypesTests/GraphQLSupportedTypesTestsBase.cs#L72-L74

### PR DESCRIPTION
**Pull request by Surya056**
## Why make this change?

- Closes #2255 

## What is this change?

- modified the duplicate SMALLDATETIME_TYPE and DisplayName for the DataRow to Sequential values.

## How was this tested?

- [x] Integration Tests
- [ ] Unit Tests

### CODE REVIEW

**Comment by Surya056** [comment]
@seantleonard   - Can you please check and let me know if any changes need to be made? Thank you!

**Review by seantleonard — APPROVED** [review]

**Review by aaronburtle — APPROVED** [review]
Thanks for fixing this!

**Comment by Surya056** [comment]
Hi @seantleonard  - there is a unit test check that failed which is not related to this change, can you please help me close this issue?

**Comment by seantleonard** [comment]
Hi @Surya056, yes, there was #2264 I needed to merge to get this working. Merged now at set your PR to auto-merge. Thank you again for your contribution!

**Pull request merged**
