### PR TITLE
Upgrade HotChocolate

### PR DESCRIPTION
**Pull request by Aniruddh25**
## Why make this change?

- Pick up latest patch version for HotChocolate 12 for bug fixes.

## What is this change?

- Upgrade the patch version number in the global properties for all HotChocolate.* packages

## How was this tested?
- Verified BCP is launched for local dev and can query GraphQL.
- Existing integration tests -fix some to accommodate how upgraded hotchocolate behaves

### CODE REVIEW

**Review by seantleonard — CHANGES_REQUESTED** [review]
are the failing tests a result of this change or transient that would resolve on pipeline retry?

**Comment by Aniruddh25** [comment]
> are the failing tests a result of this change or transient that would resolve on pipeline retry?

some of them were due to this change since hotchocolate changed the response codes, I tested with previous version - 0.8.49... 
I have modified the expected response accordingly since this is out of our control. Moving to different response codes shouldnt be a breaking change. Waiting on some Pg/MySql tests as well.

**Review by seantleonard — APPROVED** [review]
thanks for keeping dependencies up to date!

**Review by abhishekkumams — APPROVED** [review]

**Review by aaronburtle — APPROVED** [review]
Looks good!

**Pull request merged**
